# Generated by Django 6.0.3 on 2026-03-28 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lekarz',
            fields=[
                ('lekarz_id', models.AutoField(primary_key=True, serialize=False)),
                ('imie', models.CharField(max_length=50)),
                ('nazwisko', models.CharField(max_length=100)),
                ('specjalizacja', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['nazwisko', 'imie'],
            },
        ),
        migrations.CreateModel(
            name='Urzadzenie',
            fields=[
                ('urzadzenie_id', models.AutoField(primary_key=True, serialize=False)),
                ('nazwa', models.CharField(max_length=100)),
                ('typ_urzadzenia', models.CharField(max_length=50)),
                ('producent', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('numer_seryjny', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['nazwa', 'model'],
            },
        ),
        migrations.CreateModel(
            name='Pacjent',
            fields=[
                ('pacjent_id', models.AutoField(primary_key=True, serialize=False)),
                ('imie', models.CharField(max_length=50)),
                ('nazwisko', models.CharField(max_length=100)),
                ('data_urodzenia', models.DateField()),
                ('plec', models.CharField(choices=[('K', 'Kobieta'), ('M', 'Mężczyzna')], max_length=1)),
                ('pesel', models.CharField(max_length=11, unique=True)),
                ('lekarz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacjenci', to='monitoring.lekarz')),
            ],
            options={
                'ordering': ['nazwisko', 'imie'],
            },
        ),
        migrations.CreateModel(
            name='Pomiar',
            fields=[
                ('pomiar_id', models.AutoField(primary_key=True, serialize=False)),
                ('typ_pomiaru', models.CharField(max_length=50)),
                ('pomiar_start', models.DateTimeField()),
                ('pomiar_koniec', models.DateTimeField()),
                ('srednie_tetno', models.PositiveIntegerField()),
                ('min_tetno', models.PositiveIntegerField()),
                ('max_tetno', models.PositiveIntegerField()),
                ('rmssd', models.DecimalField(decimal_places=2, max_digits=6)),
                ('sdnn', models.DecimalField(decimal_places=2, max_digits=6)),
                ('sbp', models.PositiveIntegerField(verbose_name='Średnie ciśnienie skurczowe')),
                ('dbp', models.PositiveIntegerField(verbose_name='Średnie ciśnienie rozkurczowe')),
                ('pacjent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pomiary', to='monitoring.pacjent')),
                ('urzadzenie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pomiary', to='monitoring.urzadzenie')),
            ],
            options={
                'ordering': ['-pomiar_start'],
            },
        ),
    ]
